### ISSUE TITLE
'config/yolov3.weights'

### ISSUE THREAD

**Issue by Code-King** [openremote/or-objectdetection#42]
Do we have a copy of this File ?

**Comment by Code-King** [comment]
Download the correct Version of the code Fixes this issue

**Comment by Code-King** [comment]
This issues Fixed, downlaod_weight.sh did not run  automatically

Fixed issue by downloading Weights File 

Link to download Weights
https://pjreddie.com/media/files/yolov3.weights

**Comment by LuukEbenau** [comment]
glad to see it's fixed!
