### ISSUE TITLE
which docker image to be used?

### ISSUE THREAD

**Issue by ashutoshdhanda** [openremote/or-objectdetection#52]
Hello,

I just loved the project and would like to first of all congratulate you all for such an amazing work.

After having tried a lot  to install the dependencies via pip and replicate the environment, I was not able to make the code run. The OpenCV window is opening but nothing is seen. I figure that this has got something to do with the improper installation of the required packages so I decided to go the docker way, (though I'm new to docker as well).

So I used the dockerfile inside the 'yolo_object_detection' folder, and it downloaded a number of images, dependencies, etc.
![ksnip_20201216-174948](https://user-images.githubusercontent.com/9572065/102404908-1ea36a80-3fc7-11eb-9b81-f7954f84b61a.jpg)

My question is, which image do I use to run the app? Do I need to run it via anaconda?

I would appreciate your help, a lot.

Thanks

**Comment by LuukEbenau** [comment]
Hey ashutoshdhanda,

Glad to hear your enthausiasm on the project.

We have just released a major update on the application, which also inclused a docker-compose file which should be as good as plug and play.
Make sure you have the right NVIDIA cuda version, and it should be plug&play with "sudo docker-compose up"
![image](https://user-images.githubusercontent.com/45255779/104585428-44726c80-5664-11eb-9bfd-4c4c31114148.png)

For instructions see the youtube video in the readme file

**Comment by ashutoshdhanda** [comment]
Excellent. I was checking the same, last night; saw the timestamps on the recent commits and it gave new hope. Will try the updates as soon as possible and let you know. Keep up the good work. 🙏🏽
