### ISSUE TITLE
Cannot Run First Step (newbie here / need help)

### ISSUE THREAD

**Issue by manugrec** [openremote/or-objectdetection#55]
Hi Guys. 
I'm new to the coding world so please be kind. 
I have followed the steps and installed the required software etc. 
I'm using Anaconda terminal and when I try to run gui.py this message is showing up. Any feedback please?

Thanks
![Help](https://user-images.githubusercontent.com/76906777/103479309-2b003380-4dcd-11eb-8a07-839362959614.PNG)

**Comment by LuukEbenau** [comment]
you have probably accidently added a space / tab somewhere.
But the major new update of the project has been released now, so the application is now web-based and dockerized.
